version: "3"
services:

  explora_vr_cache:
    #image: gitlab.ilabt.imec.be:4567/lordezan/explora-vr-cache:latest
    build: .
    container_name: "explora_vr_cache"
    environment:
      - FLASK_APP=run.py
      - APP_SETTINGS=production
      - QUERY_LOG=./issued_queries.log
      - ENABLE_PREFETCHING=true
      - BUFFER_SEQ_LENGTH=4
      - BUFFER_SIZE=4
      - SERVER_URL=http://explora_vr_server:80
      - PERFECT_PREDICTION=true
      - ENABLE_TC=true
      - BANDWIDTH=12Mbps
      - LATENCY=15ms
      - JITTER=1.5ms
    ports:
      - "88:88"
    depends_on:
      - explora_vr_server
    cap_add:
      - NET_ADMIN
    command: ./start.sh

  explora_vr_server:
    #image: gitlab.ilabt.imec.be:4567/lordezan/explora-vr-server:latest
    build: ../explora-vr-server
    container_name: "explora_vr_server"
    environment:
      - FLASK_APP=run.py
      - APP_SETTINGS=production
      - QUERY_LOG=./issued_queries.log
      - ENABLE_TC=true
      - BANDWIDTH=12Mbps
      - LATENCY=15ms
      - JITTER=1.5ms
    volumes:
      - ../explora-vr-server/app/static:/app/app/static:ro
    ports:
        - 80:80
    cap_add:
      - NET_ADMIN
    command: ./start.sh