version: "3"
services:

  explora_vr_cache:
    #image: gitlab.ilabt.imec.be:4567/lordezan/explora-vr-cache:latest
    build: .
    container_name: "explora_vr_cache"
    environment:
      - FLASK_APP=run.py
      - APP_SETTINGS=production
      - QUERY_LOG=./issued_queries.log
      - ENABLE_PREFETCHING=true
      - BUFFER_SEQ_LENGTH=4
      - BUFFER_SIZE=10
      - SERVER_URL=http://explora_vr_server:80
      - SERVER_HOST=explora_vr_server
      - PERFECT_PREDICTION=true
      - REDIS_HOST=redis
      - ENABLE_TC=true
      - BANDWIDTH=12Mbps
      - LATENCY=15
      - JITTER=2
    ports:
      - 88:88
    depends_on:
      - explora_vr_server
      - redis
    cap_add:
      - NET_ADMIN
    command: ./start.sh

  explora_vr_server:
    #image: gitlab.ilabt.imec.be:4567/lordezan/explora-vr-server:latest
    build: ../explora-vr-server
    container_name: "explora_vr_server"
    environment:
      - FLASK_APP=run.py
      - APP_SETTINGS=production
      - QUERY_LOG=./issued_queries.log
      - ENABLE_TC=false
      - BANDWIDTH=12Mbps
      - LATENCY=15ms
      - JITTER=1.5ms
    volumes:
      - ../explora-vr-server/app/static:/app/app/static:ro
    ports:
      - 80:80
    cap_add:
      - NET_ADMIN
    command: ./start.sh

  explora_vr_client:
    #image: gitlab.ilabt.imec.be:4567/lordezan/explora-vr-client:latest
    build: ../explora-vr-client
    container_name: "explora_vr_client"
    user: root
    environment:
      - SERVER_HOST=explora_vr_server
      - SERVER_PORT=80
      - CACHE_HOST=explora_vr_cache
      - CACHE_PORT=88
      - ENABLE_TC=true
      - BANDWIDTH=12Mbps
      - LATENCY=15
      - JITTER=2
      - GRANT_SUDO=yes
    volumes:
      - ../explora-vr-client:/home/jovyan/code/explora-vr-client/
    ports:
      - 8888:8888
    cap_add:
      - NET_ADMIN
    command: ["start.sh", "jupyter", "lab" , "--ServerApp.token=''"]

  redis:
    image: "redis:alpine"
    container_name: "redis"
    ports:
        - 6379:6379