---
apiVersion: v1
kind: ConfigMap
metadata:
  name: explora-vr-cache-config
  labels:
    app: explora-vr-cache
data:
  FLASK_APP: 'run.py'
  APP_SETTINGS: 'production'
  QUERY_LOG: './issued_queries.log'
  ENABLE_PREFETCHING: 'true'
  VIEWPORT_SIZE: '-1'
  BUFFER_SIZE: '10'
  SERVER_URL: 'http://10.10.139.123:30080'
  SERVER_HOST: '10.10.139.123'
  CLIENT_HOST: '10.10.139.123'
  PERFECT_PREDICTION: 'false'
  REDIS_HOST: 'localhost'
  ENABLE_TC: 'false'
  BANDWIDTH: '25mbit'
  LATENCY: '5'
  JITTER: '0'
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: explora-vr-cache
  name: explora-vr-cache
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: explora-vr-cache
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: explora-vr-cache-config
        image: gitlab.ilabt.imec.be:4567/lordezan/explora-vr-cache
        name: explora-vr-cache
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred    
status: {}
